# Generated by Django 4.1 on 2022-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
